# Generated by Django 4.2.1 on 2023-05-15 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=0, max_digits=3)),
                ('measured_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField()),
            ],
        ),
    ]
